### ISSUE TITLE
Can't run gnome tweaks

### ISSUE THREAD

**Issue by paulosmolski** [deuill/i3-gnome-flashback#10]
Hi, firstly I'd like to thank you for the work you've done. It makes i3 so much better. Unfortunately I'm not able to run Gnome Tweaks - a crucial app in Gnome suite. 

When I type gnome-tweaks in terminal I get a following error:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/gtweak/app.py", line 30, in do_activate
    self.win = Window(self, model)
  File "/usr/lib/python3.9/site-packages/gtweak/tweakview.py", line 59, in __init__
    self._model.load_tweaks(self)
  File "/usr/lib/python3.9/site-packages/gtweak/tweakmodel.py", line 107, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/usr/lib/python3.9/site-packages/gtweak/tweaks/tweak_group_workspaces.py", line 170, in <module>
    sw = StaticWorkspaceTweak(size_group=sg, loaded=_shell_loaded)
  File "/usr/lib/python3.9/site-packages/gtweak/tweaks/tweak_group_workspaces.py", line 46, in __init__
    self.check1.set_visible(self.settings[self.key_name])
TypeError: 'GSettingsFakeSetting' object is not subscriptable
 
I run the latest version of Arch. I've tried using gnome tweaks on regolith linux - I've also tried using Gnome Tweaks on Regolith Linux (live boot). Everything worked fine there - so I guess that's not the fault of gnome flashback.

**Comment by deuill** [comment]
If you've updated recently -- this might be an issue with Gnome 40 packages that have been making their way into Arch. I haven't updated my system yet to confirm, and I can't promise I can check before the weekend, but I'll give this a try as soon as I can and return with some info.

**Comment by SkyyySi** [comment]
While this doesn't solve the issue, you can use both the `gsettings` command and the graphical dconf-editor program to do everything GNOME tweaks can (plus a lot more)

**Comment by muktupavels** [comment]
Looks like bug in `gnome-tweaks` - some Python error...

You can avoid this problem by installing `mutter`. Or you can manually copy missing `org.gnome.mutter.gschema.xml` file from somewhere. You will need to recompile using `glib-compile-schemas` (https://developer.gnome.org/gio/stable/glib-compile-schemas.html).

**Comment by paulosmolski** [comment]
@deuill Yeah Gnome 40 combined with gnome-tweaks 3.34 don't make up a great mix
@SkyyySi Already using that. Definitely more powerful but probably an overkill

**Comment by paulosmolski** [comment]
> Looks like bug in `gnome-tweaks` - some Python error...
> 
> You can avoid this problem by installing `mutter`. Or you can manually copy missing `org.gnome.mutter.gschema.xml` file from somewhere. You will need to recompile using `glib-compile-schemas` (https://developer.gnome.org/gio/stable/glib-compile-schemas.html).

Installing mutter solved this issue. Thank you
