### ISSUE TITLE
GNOME 3.36 Compatibility

### ISSUE THREAD

**Issue by deuill** [deuill/i3-gnome-flashback#8]
GNOME 3.36 is out (and already available on certain distributions, such as Arch Linux), and certain aspects of GNOME-Flashback have also changed. This issue catalogues known issues and possible solutions, which will potentially be automated in the future. That said, none of the core session files need any updates this time around, and will work out-the-box.

**Desktop is managed by GNOME Flashback, including desktop icons.** This unfortunately isn't handled as a background window, but as an invisible window (which can be killed as with any other window). You can disable desktop handling by turning `org.gnome.gnome-flashback.desktop` off, which will have the "desktop" window disappear. This will also have GNOME Flashback not handle setting the wallpaper, however, which you can enable selectively by turning `org.gnome.gnome-flashback.root-background` on.

**Screensaver capabilities are now handled within GNOME Flashback itself.** This means you no longer require having `gnome-screensaver` installed, and can activate the lock screen by sending a DBus command, i.e.:

```
dbus-send --type=method_call --dest=org.gnome.ScreenSaver /org/gnome/ScreenSaver org.gnome.ScreenSaver.Lock
```

**Comment by deuill** [comment]
It also appears that starting a new session will change back to GDM/TTY1 after a few seconds. Changing to TTY2 or logging in again works and doesn't show the issue again.

**Comment by kgilmer** [comment]
Thank you for providing this information @deuill , it's very helpful! :smile:

**Comment by omeid** [comment]
Also, to disable the Desktop window in 3.36:
`dconf write /org/gnome/gnome-flashback/desktop false`.

**Comment by SkyyySi** [comment]
I made a fork to do this automatically. Maybe not the most elegant way, but it seems to work: https://github.com/SkyyySi/i3-gnome-flashback/

**Comment by SkyyySi** [comment]
Is there any chance it'll get merged? I cannot open a proper pull request for it, as it was uploaded as a new repository (since you can only have on fork at once) sadly.

**Comment by deuill** [comment]
Oh sure, I'll take a look at the changes and open a PR.

**Comment by deuill** [comment]
PR opened in #9
